# Generated by Django 5.1.7 on 2026-04-15 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('color', models.CharField(default='#94a3b8', max_length=7)),
                ('transaction_type', models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход'), ('both', 'Оба')], default='expense', max_length=10)),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('interval', models.CharField(choices=[('monthly', 'Ежемесячно'), ('weekly', 'Еженедельно')], max_length=20)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('next_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Повторяющееся правило',
                'verbose_name_plural': 'Повторяющиеся правила',
                'ordering': ['next_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='tracker.category')),
                ('recurring_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tracker.recurringrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user'], name='tracker_cat_user_id_4a099f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'is_hidden'], name='tracker_cat_user_id_913f45_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-date'], name='tracker_tra_user_id_b536e2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='tracker_tra_user_id_ea3525_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='tracker_tra_user_id_e4d884_idx'),
        ),
    ]
