# Generated by Django 5.1.7 on 2026-04-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_seed_system_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='box', max_length=50),
        ),
    ]
